// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let limit = 4000000

let rec fib n =
    match n with
    | 0 -> 0
    | 1 -> 1
    | _ -> fib ( n - 1 ) + fib ( n - 2 ) 

let answer = // 4613732
    Seq.initInfinite (fun n -> n + 1)
    |> Seq.map fib
    |> Seq.filter (fun n -> n % 2 = 0)
    |> Seq.takeWhile (fun n -> n < limit)
    |> Seq.sum
